# Generated by Django 5.2.4 on 2025-08-14 19:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bill_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='saved_amount',
            new_name='current_amount',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(default=datetime.date(2030, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='due_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
        migrations.CreateModel(
            name='SmartShoppingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
