# Generated by Django 5.2.4 on 2025-08-14 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_rename_name_bill_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reminder_type', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CHILD_EXPENSE', "Children's Expense"), ('MEDICINE', 'Medicine Reminder'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='ONCE', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
