# Generated by Django 5.2.3 on 2026-05-20 11:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='current_amount',
            new_name='saved_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_type',
        ),
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartshoppingreminder',
            name='suggested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='due_date',
            field=models.DateField(),
        ),
    ]
